app:
  image: 'firstandthird/node:8.8-dev-root'
  volumes:
    - './:/home/app/src'
    - '/var/run/docker.sock:/var/run/docker.sock'
  ports:
    - 8080:8080
  environment:
    TOKEN:
    DOCKER_AUTH:
