app:
  dockerfile: 'DockerfileDev'
  build: '.'
  volumes:
    - './:/home/app/src'
    - '/var/run/docker.sock:/var/run/docker.sock'
  ports:
    - 8080:8080
  environment:
    TOKEN:
    DOCKER_AUTH:
